// fetch('https://jsonplaceholder.typicode.com/posts')
fetch('https://jsonplaceholder.typicode.com/users')
  .then(response => response.json())
//   .then(data => console.log(data))
  .then(data => console.log(data))